### ISSUE TITLE
What is wrong about emoji

### ISSUE THREAD

**Issue by fanlyze** [erikmartinjordan/react-emoji-textarea#1]
when i use react-emoji-textarea，the emoji display abnormal .
![20180531222431](https://user-images.githubusercontent.com/35338391/40788001-94007706-6521-11e8-9578-480a12ef02cf.png)

**Comment by fanlyze** [comment]
the code is
`import EmojiTextarea from './react-emoji-textarea';`
`<div className={style.interactContain}>
     <EmojiTextarea handleChange = {this.handleChange} handleSubmit = {this.handleSubmit} />
 </div>`

**Comment by fanlyze** [comment]
<div className={style.interactContain}>
     <EmojiTextarea handleChange = {this.handleChange} handleSubmit = {this.handleSubmit} />
 </div>

**Comment by erikmartinjordan** [comment]
The emoji face activates/deactivates the use of emojis. By default it will show emojies while typing, but if you click on that face, it will prevent to show them.
